adj1 = input("\nEnter an adjective: ")
nationality = input("Enter a nationality: ")
name = input("Enter a name: ")
noun1 = input("Enter a noun: ")
adj2 = input("Enter an adjective: ")
noun2 = input("Enter a noun: ")
adj3 = input("Enter an adjective: ")
adj4 = input("Enter an adjective: ")
plural_noun = input("Enter a plural noun: ")
noun3 = input("Enter a noun: ")
number1 = input("Enter a number: ")
shape = input("Enter a shape: ")
food1 = input("Enter a food: ")
food2 = input("Enter a food: ")
number2 = input("Enter a number: ")

print("\nHere is your Mad Lib:")
print(f"\nPizza was invented by a {adj1} {nationality} chef named {name}. To make")
print(f"a pizza, you need to make a lump of {noun1}, and make a thin, round")
print(f"{adj2} {noun2}. Then you cover it with {adj3} sauce, {adj4} cheese,")
print(f"and fresh chopped {plural_noun}. Next you have to bake it in a very")
print(f"hot {noun3}. When it is done, cut it into {number1} {shape}. Some")
print(f"kids like {food1} pizza the best, but my favorite is the {food2}")
print(f"pizza. If I could, I would eat pizza {number2} times a day!\n")